package com.example.museumapp.models.detailModels

import com.google.gson.JsonElement
import com.google.gson.annotations.SerializedName

data class DetailArtObject(
    @SerializedName("Links") val links: DetailLinks? = null,
    val id: String? = null,
    val priref: String? = null,
    val objectNumber: String? = null,
    val language: String? = null,
    val title: String? = null,
    val copyrightHolder: JsonElement? = null,
    val webImage: WebImage? = null,
    val colors: List<Color>? = null,
    val colorsWithNormalization: List<ColorsWithNormalization>? = null,
    val normalizedColors: List<Color>? = null,
    val normalized32Colors: List<Color>? = null,
    val titles: List<String>? = null,
    val description: String? = null,
    val labelText: JsonElement? = null,
    val objectTypes: List<String>? = null,
    val objectCollection: List<String>? = null,
    val makers: JsonElement? = null,
    val principalMakers: List<PrincipalMaker>? = null,
    val plaqueDescriptionDutch: String? = null,
    val plaqueDescriptionEnglish: String? = null,
    val principalMaker: String? = null,
    val artistRole: JsonElement? = null,
    val associations: JsonElement? = null,
    val acquisition: Acquisition? = null,
    val exhibitions: JsonElement? = null,
    val materials: List<String>? = null,
    val techniques: JsonElement? = null,
    val productionPlaces: List<String>? = null,
    val dating: Dating? = null,
    val classification: Classification? = null,
    val hasImage: Boolean? = null,
    val historicalPersons: List<String>? = null,
    val inscriptions: JsonElement? = null,
    val documentation: List<String>? = null,
    val catRefRPK: JsonElement? = null,
    val principalOrFirstMaker: String? = null,
    val dimensions: List<Dimension>? = null,
    val physicalProperties: JsonElement? = null,
    val physicalMedium: String? = null,
    val longTitle: String? = null,
    val subTitle: String? = null,
    val scLabelLine: String? = null,
    val label: Label? = null,
    val showImage: Boolean? = null,
    val location: String? = null
)
